apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
        - name: tripviewer
          image: registryyoy9492.azurecr.io/tripviewer:latest
          ports:
            - containerPort: 80
          env:
            - name: USERPROFILE_API_ENDPOINT
              value: http://10.0.214.142:80
            - name: TRIPS_API_ENDPOINT
              value: http://10.0.47.222:80
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer-svc
  namespace: web
  labels:
    run: tripviewer-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tripviewer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: tripviewer-ingress
  namespace: web
spec:
  rules:
    - host: aksteam7.eastasia.cloudapp.azure.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: tripviewer-svc
              port:
                number: 80
