apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registryyoy9492.azurecr.io/user-java:latest
        ports:
        - containerPort: 80
        env: 
          - name: SQL_SERVER 
            valueFrom: 
              secretKeyRef: 
                name: sqlauth 
                key: sql_fqdn 
          - name: SQL_USER 
            valueFrom: 
              secretKeyRef: 
                name: sqlauth 
                key: sql_user 
          - name: SQL_PASSWORD 
            valueFrom: 
              secretKeyRef: 
                name: sqlauth 
                key: sql_password