apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryyoy9492.azurecr.io/poi:latest
        ports:
        - containerPort: 80
        env: 
          - name: CONFIG_FILES_PATH 
            value: "/mnt/secrets-store"
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "akstask5vault"
---
apiVersion: v1
kind: Service
metadata:
  name: poi-svc
  namespace: api
  labels:
    run: poi-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: poi
