apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registryyoy9492.azurecr.io/trips:latest
        ports:
        - containerPort: 80
        env: 
          - name: SQL_SERVER 
            valueFrom: 
              secretKeyRef: 
                name: sqlauth 
                key: sql_fqdn 
          - name: SQL_USER 
            valueFrom: 
              secretKeyRef: 
                name: sqlauth 
                key: sql_user 
          - name: SQL_PASSWORD 
            valueFrom: 
              secretKeyRef: 
                name: sqlauth 
                key: sql_password 
          - name: OPENAPI_DOCS_URI
            value: http://localhost
---
apiVersion: v1
kind: Service
metadata:
  name: trips-svc
  namespace: api
  labels:
    run: trips-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: trips