apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registryyoy9492.azurecr.io/trips:latest
        ports:
          - containerPort: 80
        env:
          - name: CONFIG_FILES_PATH
            value: "/mnt/secrets-store"
          - name: OPENAPI_DOCS_URI
            value: http://localhost
        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "akstask5vault"
---
apiVersion: v1
kind: Service
metadata:
  name: trips-svc
  namespace: api
  labels:
    run: trips-svc
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: trips
