apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registryyoy9492.azurecr.io/user-java:latest
        ports:
        - containerPort: 80
        env: 
          - name: CONFIG_FILES_PATH 
            value: "/mnt/secrets-store"
          - name: OPENAPI_DOCS_URI
            value: http://localhost
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "akstask5vault"
---
apiVersion: v1
kind: Service
metadata:
  name: user-java-svc
  namespace: api
  labels:
    run: user-java-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: user-java