apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryyoy9492.azurecr.io/userprofile:latest
        ports:
        - containerPort: 80
        env: 
          - name: SQL_SERVER 
            valueFrom: 
              secretKeyRef: 
                name: sqlauth 
                key: sql_fqdn 
          - name: SQL_USER 
            valueFrom: 
              secretKeyRef: 
                name: sqlauth 
                key: sql_user 
          - name: SQL_PASSWORD 
            valueFrom: 
              secretKeyRef: 
                name: sqlauth 
                key: sql_password