apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: akstask5vault
  namespace: api
spec:
  provider: azure
  parameters:
    keyvaultName: "akstask5vault"       # The name of the Azure Key Vault
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: "fc61674a-5e4b-44c0-9849-94dfa445cc0b" # The clientId of the addon-created managed identity
    objects:  |
      array:
        - |
          objectName: "SQLSERVER"       # In this example, 'ExampleSecret'
          objectAlias: "SQL_SERVER"
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: "SQLUSER"       # In this example, 'ExampleSecret'   
          objectAlias: "SQL_USER"
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: "SQLPASSWORD"       # In this example, 'ExampleSecret'   
          objectAlias: "SQL_PASSWORD"
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    tenantId: "3c3b6e87-a8fc-4649-88c3-7bd2179a1fea"               # the tenant ID containing the Azure Key Vault instance